name: tp1
services:
  rabbitmq:
    container_name: rabbitmq
    image: rabbitmq:4-management
    ports:
      - 5672:5672
      - 15672:15672
    networks:
      - net
    healthcheck:
      test: ["CMD", "rabbitmqctl", "status"]
      interval: 5s
      timeout: 5s
      retries: 3

  gateway:
    container_name: gateway
    image: tp1:latest
    entrypoint: /gateway
    environment:
      - RABBIT_IP=rabbitmq
    networks:
      - net
    depends_on:
      rabbitmq:
        condition: service_healthy

  client:
    container_name: client
    image: tp1:latest
    entrypoint: /client
    environment:
      - GATEWAY_CONN_ADDR=gateway:9001
      - GATEWAY_DATA_ADDR=gateway:9002
    volumes:
      - ./.data:/.data
    networks:
      - net
    depends_on:
      - gateway

  partitioner:
    container_name: partitioner
    image: tp1:latest
    entrypoint: /game-partitioner
    environment:
      - RABBIT_IP=rabbitmq
      - INPUT_QUEUE=games-per-platform
      - PARTITIONS_NUMBER=3
    networks:
      - net
    depends_on:
      - gateway

  genre-filter:
    container_name: genre-filter
    image: tp1:latest
    entrypoint: /genre-filter
    environment:
      - RABBIT_IP=rabbitmq
    networks:
      - net
    depends_on:
      - gateway

  decade-filter:
    container_name: decade-filter
    image: tp1:latest
    entrypoint: /decade-filter
    environment:
      - RABBIT_IP=rabbitmq
      - DECADE=2010
    networks:
      - net
    depends_on:
      - gateway

  review-filter:
    container_name: review-filter
    image: tp1:latest
    entrypoint: /review-filter
    environment:
      - RABBIT_IP=rabbitmq
    networks:
      - net
    depends_on:
      - gateway

  language-filter:
    container_name: language-filter
    image: tp1:latest
    entrypoint: /language-filter
    environment:
      - RABBIT_IP=rabbitmq
    networks:
      - net
    depends_on:
      - gateway

  games-per-platform-1:
    container_name: games-per-platform-1
    image: tp1:latest
    entrypoint: /games-per-platform
    environment:
      - RABBIT_IP=rabbitmq
      - PARTITION_ID=0
    networks:
      - net
    depends_on:
      - gateway

  games-per-platform-2:
    container_name: games-per-platform-2
    image: tp1:latest
    entrypoint: /games-per-platform
    environment:
      - RABBIT_IP=rabbitmq
      - PARTITION_ID=1
    networks:
      - net
    depends_on:
      - gateway

  games-per-platform-3:
    container_name: games-per-platform-3
    image: tp1:latest
    entrypoint: /games-per-platform
    environment:
      - RABBIT_IP=rabbitmq
      - PARTITION_ID=2
    networks:
      - net
    depends_on:
      - gateway

  games-per-platform-joiner:
    container_name: games-per-platform-joiner
    image: tp1:latest
    entrypoint: /games-per-platform-joiner
    environment:
      - RABBIT_IP=rabbitmq
      - PARTITIONS=3
    networks:
      - net
    depends_on:
      - gateway

  top-n-amount-games-partitioner:
    image: tp1:latest
    entrypoint: /game-partitioner
    environment:
      - RABBIT_IP=rabbitmq
      - INPUT_QUEUE=games-top-n-amount-reviews
      - PARTITIONS_NUMBER=1
    networks:
      - net
    depends_on:
      - gateway

  top-n-amount-reviews-partitioner:
    image: tp1:latest
    entrypoint: /game-partitioner
    environment:
      - RABBIT_IP=rabbitmq
      - INPUT_QUEUE=reviews-top-n-partitioner
      - PARTITIONS_NUMBER=1
    networks:
      - net
    depends_on:
      - gateway

  top-n-amount-group-by-game:
    image: tp1:latest
    entrypoint: /group-by-game
    environment:
      - RABBIT_IP=rabbitmq
      - GAME_INPUT=games-top-n-amount-reviews
      - REVIEW_INPUT=reviews-top-n-partitioner
      - PARTITION_ID=0
    networks:
      - net
    depends_on:
      - gateway

networks:
  net:
