name: tp1
services:
  restarter-0:
    container_name: restarter-0
    image: tp1:latest
    entrypoint: /build/restarter
    environment:
      - ID=0
      - ADDRESS=restarter-0:14300
      - NEIGHBOR_ADDRESS=restarter-1:14301
    networks:
      - net
  restarter-1:
    container_name: restarter-1
    image: tp1:latest
    entrypoint: /build/restarter
    environment:
      - ID=1
      - ADDRESS=restarter-1:14301
      - NEIGHBOR_ADDRESS=restarter-2:14302
    networks:
      - net
  restarter-2:
    container_name: restarter-2
    image: tp1:latest
    entrypoint: /build/restarter
    environment:
      - ID=2
      - ADDRESS=restarter-2:14302
      - NEIGHBOR_ADDRESS=restarter-3:14303
    networks:
      - net
  restarter-3:
    container_name: restarter-3
    image: tp1:latest
    entrypoint: /build/restarter
    environment:
      - ID=3
      - ADDRESS=restarter-3:14303
      - NEIGHBOR_ADDRESS=restarter-0:14300
    networks:
      - net
networks:
  net:
