name: tp1
services:
  rabbitmq:
    container_name: rabbitmq
    image: rabbitmq:4-management
    ports:
      - 5672:5672
      - 15672:15672
    networks:
      - net
    healthcheck:
      test: ["CMD", "rabbitmqctl", "status"]
      interval: 5s
      timeout: 5s
      retries: 3
    logging:
      driver: none
  gateway:
    container_name: gateway
    image: tp1:latest
    entrypoint: /build/gateway
    environment:
      - RABBIT_IP=rabbitmq
    networks:
      - net
    depends_on:
      rabbitmq:
        condition: service_healthy
  genre-filter-1:
    container_name: genre-filter-1
    image: tp1:latest
    entrypoint: /build/filter-genre
    environment:
      - RABBIT_IP=rabbitmq
      - ADDRESS=genre-filter-1:7000
    networks:
      - net
    depends_on:
      - gateway
  decade-filter-1:
    container_name: decade-filter-1
    image: tp1:latest
    entrypoint: /build/filter-decade
    environment:
      - RABBIT_IP=rabbitmq
      - DECADE=2010
      - ADDRESS=decade-filter-1:7000
    networks:
      - net
    depends_on:
      - gateway
  review-filter-1:
    container_name: review-filter-1
    image: tp1:latest
    entrypoint: /build/filter-score
    environment:
      - RABBIT_IP=rabbitmq
      - ADDRESS=review-filter-1:7000
    networks:
      - net
    depends_on:
      - gateway
  language-filter-1:
    container_name: language-filter-1
    image: tp1:latest
    entrypoint: /build/filter-language
    environment:
      - RABBIT_IP=rabbitmq
      - ADDRESS=language-filter-1:7000
    networks:
      - net
    depends_on:
      - gateway
  q1-partitioner:
    container_name: q1-partitioner
    image: tp1:latest
    entrypoint: /build/partitioner
    environment:
      - RABBIT_IP=rabbitmq
      - INPUT=games-Q1
      - PARTITIONS=1
      - ADDRESS=q1-partitioner:7000
      - TYPE=game
    networks:
      - net
    depends_on:
      - gateway
  q1-count-1:
    container_name: q1-count-1
    image: tp1:latest
    entrypoint: /build/games-per-platform
    environment:
      - RABBIT_IP=rabbitmq
      - PARTITION_ID=1
      - ADDRESS=q1-count-1:7000
    networks:
      - net
    depends_on:
      - gateway
  q1-joiner:
    container_name: q1-joiner
    image: tp1:latest
    entrypoint: /build/games-per-platform-joiner
    environment:
      - RABBIT_IP=rabbitmq
      - PARTITIONS=1
      - ADDRESS=q1-joiner:7000
    networks:
      - net
    depends_on:
      - gateway
  restarter-0:
    container_name: restarter-0
    image: tp1:latest
    entrypoint: /build/restarter
    environment:
      - ID=0
      - ADDRESS=restarter-0:14300
      - REPLICAS=1
    volumes:
      - ./.node-config.csv:/work/.node-config.csv
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - gateway
    networks:
      - net
networks:
  net:
