name: tp1
services:
  rabbitmq:
    container_name: rabbitmq
    image: rabbitmq:4-management
    ports:
      - 5672:5672
      - 15672:15672
    networks:
      - net
    healthcheck:
      test: ["CMD", "rabbitmqctl", "status"]
      interval: 5s
      timeout: 5s
      retries: 3
    logging:
      driver: none
  gateway:
    container_name: gateway
    image: tp1:latest
    entrypoint: /build/gateway
    environment:
      - RABBIT_IP=rabbitmq
    networks:
      - net
    depends_on:
      rabbitmq:
        condition: service_healthy
  client-1:
    container_name: client-1
    image: tp1:latest
    entrypoint: /build/client
    environment:
      - GATEWAY_CONN_ADDR=gateway:9001
      - GATEWAY_DATA_ADDR=gateway:9002
    volumes:
      - ./.data:/.data
      - ./.results-1:/.results
    networks:
      - net
    depends_on:
      - gateway
  client-2:
    container_name: client-2
    image: tp1:latest
    entrypoint: /build/client
    environment:
      - GATEWAY_CONN_ADDR=gateway:9001
      - GATEWAY_DATA_ADDR=gateway:9002
    volumes:
      - ./.data:/.data
      - ./.results-2:/.results
    networks:
      - net
    depends_on:
      - gateway
  client-3:
    container_name: client-3
    image: tp1:latest
    entrypoint: /build/client
    environment:
      - GATEWAY_CONN_ADDR=gateway:9001
      - GATEWAY_DATA_ADDR=gateway:9002
    volumes:
      - ./.data:/.data
      - ./.results-3:/.results
    networks:
      - net
    depends_on:
      - gateway
  genre-filter:
    image: tp1:latest
    entrypoint: /build/filter-genre
    environment:
      - RABBIT_IP=rabbitmq
    networks:
      - net
    depends_on:
      - gateway
    deploy:
      mode: replicated
      replicas: 1
  decade-filter:
    image: tp1:latest
    entrypoint: /build/filter-decade
    environment:
      - RABBIT_IP=rabbitmq
      - DECADE=2010
    networks:
      - net
    depends_on:
      - gateway
    deploy:
      mode: replicated
      replicas: 1
  review-filter:
    image: tp1:latest
    entrypoint: /build/filter-score
    environment:
      - RABBIT_IP=rabbitmq
    networks:
      - net
    depends_on:
      - gateway
    deploy:
      mode: replicated
      replicas: 1
  language-filter:
    image: tp1:latest
    entrypoint: /build/filter-language
    environment:
      - RABBIT_IP=rabbitmq
    networks:
      - net
    depends_on:
      - gateway
    deploy:
      mode: replicated
      replicas: 4
  q1-partitioner:
    container_name: q1-partitioner
    image: tp1:latest
    entrypoint: /build/partitioner
    environment:
      - RABBIT_IP=rabbitmq
      - INPUT=games-Q1
      - PARTITIONS=1
      - TYPE=game
    networks:
      - net
    depends_on:
      - gateway
  q1-count-1:
    container_name: q1-count-1
    image: tp1:latest
    entrypoint: /build/games-per-platform
    environment:
      - RABBIT_IP=rabbitmq
      - PARTITION_ID=1
    networks:
      - net
    depends_on:
      - gateway
  q1-joiner:
    container_name: q1-joiner
    image: tp1:latest
    entrypoint: /build/games-per-platform-joiner
    environment:
      - RABBIT_IP=rabbitmq
      - PARTITIONS=1
    networks:
      - net
    depends_on:
      - gateway
  q2-partitioner:
    container_name: q2-partitioner
    image: tp1:latest
    entrypoint: /build/partitioner
    environment:
      - RABBIT_IP=rabbitmq
      - INPUT=games-Q2
      - PARTITIONS=1
      - TYPE=game
    networks:
      - net
    depends_on:
      - gateway
  q2-top-1:
    container_name: q2-top-1
    image: tp1:latest
    entrypoint: /build/top-n-historic-avg
    environment:
      - RABBIT_IP=rabbitmq
      - PARTITION_ID=1
      - INPUT=games-Q2
      - TOP_N=10
    networks:
      - net
    depends_on:
      - gateway
  q2-joiner:
    container_name: q2-joiner
    image: tp1:latest
    entrypoint: /build/top-n-historic-avg-joiner
    environment:
      - RABBIT_IP=rabbitmq
      - PARTITIONS=1
      - INPUT=partial-Q2-joiner
      - TOP_N=10
    networks:
      - net
    depends_on:
      - gateway
  q3-games-partitioner:
    container_name: q3-games-partitioner
    image: tp1:latest
    entrypoint: /build/partitioner
    environment:
      - RABBIT_IP=rabbitmq
      - INPUT=games-Q3
      - PARTITIONS=1
      - TYPE=game
    networks:
      - net
    depends_on:
      - gateway
  q3-reviews-partitioner:
    container_name: q3-reviews-partitioner
    image: tp1:latest
    entrypoint: /build/partitioner
    environment:
      - RABBIT_IP=rabbitmq
      - INPUT=reviews-Q3
      - PARTITIONS=1
      - TYPE=review
    networks:
      - net
    depends_on:
      - gateway
  q3-group-1:
    container_name: q3-group-1
    image: tp1:latest
    entrypoint: /build/group-by
    environment:
      - RABBIT_IP=rabbitmq
      - PARTITION_ID=1
      - GAME_INPUT=games-Q3
      - REVIEW_INPUT=reviews-Q3
      - OUTPUT=grouped-Q3-top
    networks:
      - net
    depends_on:
      - gateway
  q3-top-1:
    container_name: q3-top-1
    image: tp1:latest
    entrypoint: /build/top-n-reviews
    environment:
      - RABBIT_IP=rabbitmq
      - PARTITION_ID=1
      - N=5000
    networks:
      - net
    depends_on:
      - gateway
  q3-joiner:
    container_name: q3-joiner
    image: tp1:latest
    entrypoint: /build/top-n-reviews-joiner
    environment:
      - RABBIT_IP=rabbitmq
      - TOP_N=5
      - PARTITIONS=1
    networks:
      - net
    depends_on:
      - gateway
  q4-games-partitioner:
    container_name: q4-games-partitioner
    image: tp1:latest
    entrypoint: /build/partitioner
    environment:
      - RABBIT_IP=rabbitmq
      - INPUT=games-Q4
      - PARTITIONS=1
      - TYPE=game
    networks:
      - net
    depends_on:
      - gateway
  q4-reviews-partitioner:
    container_name: q4-reviews-partitioner
    image: tp1:latest
    entrypoint: /build/partitioner
    environment:
      - RABBIT_IP=rabbitmq
      - INPUT=reviews-Q4
      - PARTITIONS=1
      - TYPE=review
    networks:
      - net
    depends_on:
      - gateway
  q4-group-1:
    container_name: q4-group-1
    image: tp1:latest
    entrypoint: /build/group-by
    environment:
      - RABBIT_IP=rabbitmq
      - PARTITION_ID=1
      - GAME_INPUT=games-Q4
      - REVIEW_INPUT=reviews-Q4
      - OUTPUT=grouped-Q4-joiner
    networks:
      - net
    depends_on:
      - gateway
  q4-joiner:
    container_name: q4-joiner
    image: tp1:latest
    entrypoint: /build/group-joiner
    environment:
      - RABBIT_IP=rabbitmq
      - PARTITIONS=1
      - INPUT=grouped-Q4-joiner
      - OUTPUT=grouped-Q4-filter
    networks:
      - net
    depends_on:
      - gateway
  q4-filter:
    container_name: q4-filter
    image: tp1:latest
    entrypoint: /build/more-than-n-reviews
    environment:
      - RABBIT_IP=rabbitmq
      - N=5000
    networks:
      - net
    depends_on:
      - gateway
  q5-games-partitioner:
    container_name: q5-games-partitioner
    image: tp1:latest
    entrypoint: /build/partitioner
    environment:
      - RABBIT_IP=rabbitmq
      - INPUT=games-Q5
      - PARTITIONS=1
      - TYPE=game
    networks:
      - net
    depends_on:
      - gateway
  q5-reviews-partitioner:
    container_name: q5-reviews-partitioner
    image: tp1:latest
    entrypoint: /build/partitioner
    environment:
      - RABBIT_IP=rabbitmq
      - INPUT=reviews-Q5
      - PARTITIONS=1
      - TYPE=review
    networks:
      - net
    depends_on:
      - gateway
  q5-group-1:
    container_name: q5-group-1
    image: tp1:latest
    entrypoint: /build/group-by
    environment:
      - RABBIT_IP=rabbitmq
      - PARTITION_ID=1
      - GAME_INPUT=games-Q5
      - REVIEW_INPUT=reviews-Q5
      - OUTPUT=grouped-Q5-joiner
    networks:
      - net
    depends_on:
      - gateway
  q5-joiner:
    container_name: q5-joiner
    image: tp1:latest
    entrypoint: /build/group-joiner
    environment:
      - RABBIT_IP=rabbitmq
      - PARTITIONS=1
      - INPUT=grouped-Q5-joiner
      - OUTPUT=grouped-Q5-percentil
    networks:
      - net
    depends_on:
      - gateway
  q5-percentile:
    container_name: q5-percentile
    image: tp1:latest
    entrypoint: /build/percentile
    environment:
      - RABBIT_IP=rabbitmq
      - PERCENTILE=90
    networks:
      - net
    depends_on:
      - gateway
networks:
  net:
