name: tp1
services:
  rabbitmq:
    container_name: rabbitmq
    image: rabbitmq:4-management
    ports:
      - 5672:5672
      - 15672:15672
    networks:
      - net
    healthcheck:
      test: [ "CMD", "rabbitmqctl", "status" ]
      interval: 5s
      timeout: 5s
      retries: 3

  gateway:
    container_name: gateway
    image: tp1:latest
    entrypoint: /gateway
    environment:
      - RABBIT_IP=rabbitmq
    networks:
      - net
    depends_on:
      rabbitmq:
        condition: service_healthy

  client:
    container_name: client
    image: tp1:latest
    entrypoint: /client
    environment:
      - GATEWAY_CONN_ADDR=gateway:9001
      - GATEWAY_DATA_ADDR=gateway:9002
    volumes:
      - ./.data:/.data
    networks:
      - net
    depends_on:
      - gateway

  genre-filter:
    container_name: genre-filter
    image: tp1:latest
    entrypoint: /genre-filter
    environment:
      - RABBIT_IP=rabbitmq
    networks:
      - net
    depends_on:
      - gateway

  decade-filter:
    container_name: decade-filter
    image: tp1:latest
    entrypoint: /decade-filter
    environment:
      - RABBIT_IP=rabbitmq
      - DECADE=2010
    networks:
      - net
    depends_on:
      - gateway

  review-filter:
    container_name: review-filter
    image: tp1:latest
    entrypoint: /review-filter
    environment:
      - RABBIT_IP=rabbitmq
    networks:
      - net
    depends_on:
      - gateway

  language-filter:
    container_name: language-filter
    image: tp1:latest
    entrypoint: /language-filter
    environment:
      - RABBIT_IP=rabbitmq
    networks:
      - net
    depends_on:
      - gateway

  q1-partitioner:
    container_name: q1-partitioner
    image: tp1:latest
    entrypoint: /partitioner
    environment:
      - RABBIT_IP=rabbitmq
      - INPUT=games-per-platform
      - PARTITIONS=2
      - TYPE=game
    networks:
      - net
    depends_on:
      - gateway

  q1-1:
    container_name: q1-1
    image: tp1:latest
    entrypoint: /games-per-platform
    environment:
      - RABBIT_IP=rabbitmq
      - PARTITION_ID=1
    networks:
      - net
    depends_on:
      - gateway

  q1-2:
    container_name: q1-2
    image: tp1:latest
    entrypoint: /games-per-platform
    environment:
      - RABBIT_IP=rabbitmq
      - PARTITION_ID=2
    networks:
      - net
    depends_on:
      - gateway

  q1-joiner:
    container_name: q1-joiner
    image: tp1:latest
    entrypoint: /games-per-platform-joiner
    environment:
      - RABBIT_IP=rabbitmq
      - PARTITIONS=2
    networks:
      - net
    depends_on:
      - gateway

  q2-games-partitioner:
      container_name: q2-games-partitioner
      image: tp1:latest
      entrypoint: /partitioner
      environment:
        - RABBIT_IP=rabbitmq
        - INPUT=top-n-historic-avg-partitioner
        - PARTITIONS=1
        - TYPE=game
      networks:
        - net
      depends_on:
        - gateway

  top-n-historic-avg-aggregator:
    container_name: top-n-historic-avg-aggregator
    image: tp1:latest
    entrypoint: /top-n-historic-avg-aggregator
    environment:
      - RABBIT_IP=rabbitmq
      - PARTITION_ID=0
      - TOP_N=10

  q3-games-partitioner:
      container_name: q3-games-partitioner
      image: tp1:latest
      entrypoint: /partitioner
      environment:
        - RABBIT_IP=rabbitmq
        - INPUT=games-top-n-amount-reviews
        - PARTITIONS=1
        - TYPE=game
      networks:
        - net
      depends_on:
        - gateway

  q3-reviews-partitioner:
    container_name: q3-reviews-partitioner
    image: tp1:latest
    entrypoint: /partitioner
    environment:
      - RABBIT_IP=rabbitmq
      - INPUT=reviews-top-n-partitioner
      - PARTITIONS=1
      - TYPE=review
    networks:
      - net
    depends_on:
      - gateway

  q3-group-1:
    container_name: q3-group-1
    image: tp1:latest
    entrypoint: /group-by-game
    environment:
      - RABBIT_IP=rabbitmq
      - GAME_INPUT=games-top-n-amount-reviews
      - REVIEW_INPUT=reviews-top-n-partitioner
      - OUTPUT=HOLA
      - PARTITION_ID=1
    networks:
      - net
    depends_on:
      - gateway

networks:
  net:
