name: tp1
services:
  rabbitmq:
    container_name: rabbitmq
    image: rabbitmq:4-management
    ports:
      - 5672:5672
      - 15672:15672
    networks:
      - net
    healthcheck:
      test: ["CMD", "rabbitmqctl", "status"]
      interval: 5s
      timeout: 5s
      retries: 3

  gateway:
    container_name: gateway
    image: tp1:latest
    entrypoint: /gateway
    environment:
      - RABBIT_IP=rabbitmq
    networks:
      - net
    depends_on:
      rabbitmq:
        condition: service_healthy

  client:
    container_name: client
    image: tp1:latest
    entrypoint: /client
    environment:
      - GATEWAY_CONN_ADDR=gateway:9001
      - GATEWAY_DATA_ADDR=gateway:9002
    volumes:
      - ./.data:/.data
    networks:
      - net
    depends_on:
      - gateway

  partitioner:
    container_name: partitioner
    image: tp1:latest
    entrypoint: /partitioner
    environment:
      - RABBIT_IP=rabbitmq
      - INPUT=games-per-platform
      - PARTITIONS=3
      - TYPE=game
    networks:
      - net
    depends_on:
      - gateway

  genre-filter:
    container_name: genre-filter
    image: tp1:latest
    entrypoint: /genre-filter
    environment:
      - RABBIT_IP=rabbitmq
    networks:
      - net
    depends_on:
      - gateway

  decade-filter:
    container_name: decade-filter
    image: tp1:latest
    entrypoint: /decade-filter
    environment:
      - RABBIT_IP=rabbitmq
      - DECADE=2010
    networks:
      - net
    depends_on:
      - gateway

  review-filter:
    container_name: review-filter
    image: tp1:latest
    entrypoint: /review-filter
    environment:
      - RABBIT_IP=rabbitmq
    networks:
      - net
    depends_on:
      - gateway

  language-filter:
    container_name: language-filter
    image: tp1:latest
    entrypoint: /language-filter
    environment:
      - RABBIT_IP=rabbitmq
    networks:
      - net
    depends_on:
      - gateway

networks:
  net:
