name: tp1
services:
  rabbitmq:
    container_name: rabbitmq
    image: rabbitmq:4-management
    ports:
      - 5672:5672
      - 15672:15672
    networks:
      - net
    healthcheck:
      test: rabbitmq-diagnostics -q ping
      interval: 5s
      timeout: 5s
      retries: 3

  gateway:
    container_name: gateway
    build: .
    entrypoint: /gateway
    environment:
      - RABBIT_IP=rabbitmq
    networks:
      - net
    depends_on:
      rabbitmq:
        condition: service_healthy

  client:
    container_name: client
    build: .
    entrypoint: /client
    environment:
      - GATEWAY_CONN_ADDR=gateway:9001
      - GATEWAY_DATA_ADDR=gateway:9002
    volumes:
      - ./.data:/.data
    networks:
      - net
    depends_on:
      - gateway

  partitioner:
    container_name: partitioner
    build: .
    entrypoint: /game-partitioner
    environment:
      - RABBIT_IP=rabbitmq
      - INPUT_QUEUE=games-partitioner
      - PARTITIONS_NUMBER=3
    networks:
      - net
    depends_on:
      - gateway

  genre-filter:
    container_name: genre-filter
    build: .
    entrypoint: /genre-filter
    environment:
      - RABBIT_IP=rabbitmq
    networks:
      - net
    depends_on:
      - gateway

  decade-filter:
    container_name: decade-filter
    build: .
    entrypoint: /decade-filter
    environment:
      - RABBIT_IP=rabbitmq
      - DECADE=2010
    networks:
      - net
    depends_on:
      - gateway

  reviews-filter:
    container_name: reviews-filter
    build: .
    entrypoint: /reviews-filter
    environment:
      - RABBIT_IP=rabbitmq
    networks:
      - net
    depends_on:
      - gateway

  language-filter:
    container_name: language-filter
    build: .
    entrypoint: /language-filter
    environment:
      - RABBIT_IP=rabbitmq
    networks:
      - net
    depends_on:
      - gateway

networks:
  net:
